version: '3.8'

services:
  whisper-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped
    container_name: whisper-api

  gentle:
    image: lowerquality/gentle
    ports:
      - "8765:8765"
    restart: unless-stopped
    container_name: gentle
